openapi: 3.0.0
info:
  title: WatchtowerX API
  version: 1.0.0
  description: Minimal OpenAPI spec for WatchtowerX
paths:
  /api/event:
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventType:
                  type: string
                  enum: [fire, fall, fight]
                timestamp:
                  type: string
                  format: date-time
                priority:
                  type: integer
                cameraId:
                  type: string
              required: [eventType, timestamp, priority, cameraId]
      responses:
        "201":
          description: Event created
  /api/events:
    get:
      summary: List events
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: page
          schema:
            type: integer
      responses:
        "200":
          description: A list of events
