components:
  schemas:
    Event:
      type: object
      properties:
        eventId:
          type: string
        eventType:
          type: string
          enum: [fire, fall, fight]
        timestamp:
          type: string
          format: date-time
        location:
          type: string
        severity:
          type: string
          enum: [low, medium, high]
        status:
          type: string
          enum: [pending, dispatched, resolved]
        notes:
          type: string
        snapshotUrl:
          type: string
          nullable: true
paths:
  /api/events:
    get:
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum: [fire, fall, fight]
          description: Filter by eventType
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                  limit:
                    type: integer
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
